# This program will spell my name
import turtle
#
dolan = turtle.Turtle()
#
dolan.color ('black')
dolan.pensize(10)
dolan.shape('turtle')
# D ***********************************************************************************************************
dolan.penup()
dolan.goto(-180,180)
dolan.right(90)
dolan.pendown()
dolan.forward(125)
dolan.right(-90)
dolan.forward(25)
dolan.left(35)
dolan.forward(25)
dolan.left(55)
dolan.forward(85)
dolan.left(35)
dolan.forward(30)
dolan.left(55)
dolan.forward(20)
# I ***********************************************************************************************************
dolan.penup()
dolan.goto(-100,50)
dolan.pendown()
dolan.right(180)
dolan.forward(65)
dolan.left(180)
dolan.forward(32.5)
dolan.right(90)
dolan.forward(125)
dolan.left(90)
dolan.forward(32.5)
dolan.right(180)
dolan.forward(65)
# L ***********************************************************************************************************
dolan.penup()
dolan.goto(15,180)
dolan.pendown()
dolan.right(90)
dolan.forward(135)
dolan.left(90)
dolan.forward(50)
# A ***********************************************************************************************************
dolan.penup()
dolan.goto(100,40)
dolan.pendown()
dolan.left(75)
dolan.forward(135)
dolan.right(150)
dolan.forward(135)
dolan.left(180)
dolan.forward(55)
dolan.left(75)
dolan.forward(40)
# N ***********************************************************************************************************
dolan.penup()
dolan.goto(-180,-90)
dolan.pendown()
dolan.right(90)
dolan.forward(125)
dolan.right(150)
dolan.forward(140)
dolan.left(150)
dolan.forward(125)
# Dilan *******************************************************************************************************
